rules:
- id: vuln-cloud-init-42788bf2
  pattern: "def rand_user_password(pwlen=9):\n    ...\n"
  pattern-not: "def rand_user_password(pwlen=20):\n    ...\n"
  languages:
  - python
  message: Detected insecure default password length in rand_user_password function.
    A default length of 9 is too short and may lead to weak passwords. Increase the
    default length to at least 20 for better security.
  severity: ERROR
  metadata:
    source-url: github.com/canonical/cloud-init/commit/42788bf24a1a0a5421a2d00a7f59b59e38ba1a14
    category: security
    cwe:
    - CWE-521
    owasp:
    - A2:2017-Broken Authentication
    technology:
    - python
